spring.profiles.active=local
# ===============================
# = JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ===============================
# = Server Port
# ===============================
server.port=8080
